creation_rules:
  - age:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICUZ+rb5WpsUv/4wVWlQ0aCRiNzZCIQngxXiNAJx6hJs # desktop
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhSmVRhMXbxDkDOaUk0udibjBos2nDg6byvZ//dzMwL # dell
      - age1zxaucdgk9gf9kntp63h9wsnkduadygetdq3lgyj05whdq6k3248qecvdfw # plex server
      - age13fh777s9rxhktee6q72aykv52kxxwlra5n5h08rr795j54s3hytqwxgx5f # Mac Pelico
