creation_rules:
    - age: >-
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICUZ+rb5WpsUv/4wVWlQ0aCRiNzZCIQngxXiNAJx6hJs,
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIfK4sKI0QpEbaADjQm/7bK3DlNY/akOh+6yC+q3aG17,
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhSmVRhMXbxDkDOaUk0udibjBos2nDg6byvZ//dzMwL,
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJa4G/kDlZHkH6mYfLzpZ2CihkOmCCoMgpQG44NJ41Y2
