export const countryISOMapping = {
  de: 'deu',
  en: 'eng',
  es: 'spa',
  fr: 'fre',
  it: 'ita',
  pt: 'por',
  nl: 'nld',
  da: 'dan',
  sv: 'swe',
  no: 'nor',
  fi: 'fin',
  is: 'isl',
  pl: 'pol',
  hu: 'hun',
  el: 'ell',
  cs: 'ces',
  sk: 'slk',
  ro: 'ron',
  bg: 'bul',
  hr: 'hrv',
  sr: 'srp',
  sl: 'slv',
  et: 'est',
  lv: 'lav',
  lt: 'lit',
  mt: 'mlt',
  zh: 'zho',
  ja: 'jpn',
  ru: 'rus',
  ar: 'ara',
  hi: 'hin',
  ko: 'kor',
  tr: 'tur',
  fa: 'fas',
  id: 'ind',
  bn: 'ben',
} as const;

export type iso1 = keyof typeof countryISOMapping;
export type iso2 = (typeof countryISOMapping)[iso1];
