export const countryISOMapping = {
  id: 'ind',
  ar: 'ara',
  bg: 'bul',
  bn: 'ben',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  el: 'ell',
  en: 'eng',
  es: 'spa',
  et: 'est',
  fa: 'fas',
  fi: 'fin',
  fr: 'fre',
  hi: 'hin',
  hr: 'hrv',
  hu: 'hun',
  is: 'isl',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  lt: 'lit',
  lv: 'lav',
  mt: 'mlt',
  nl: 'nld',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  ro: 'ron',
  ru: 'rus',
  sk: 'slk',
  sl: 'slv',
  sr: 'srp',
  sv: 'swe',
  tr: 'tur',
  zh: 'zho',
} as const

export type iso1 = keyof typeof countryISOMapping
export type iso2 = (typeof countryISOMapping)[iso1]
