services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./plex_update.sh:/app/plex_update.sh
      - ./config.yaml:/app/config.yaml
      - ${APP_PATH}/zurg:/app/data
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    extends:
      file: ../docker/compose.common.yaml
      service: common
    volumes:
      - ${APP_PATH}/zurg:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
