services:
  autolanguageconfig:
    container_name: autolanguageconfig
    build:
      context: ./autolanguageconfig/
    volumes:
      - ./treatedMedias.json:/autolanguageconfig/config/treatedMedias.json
      - ./tvdbToken.json:/autolanguageconfig/config/tvdbToken.json
      - ./.env:/autolanguageconfig/.env
    restart: unless-stopped
  autoscan:
    container_name: autoscan
    image: cloudb0x/autoscan:latest
    extends:
      file: ../docker/compose.common.yaml
      service: common
    hostname: autoscan
    volumes:
      - ./:/config
      - ${APP_PATH}/autoscan:/config
      - ./autoscan.yml:/config/config.yml
      - ${DATA_PATH}:/data
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    extends:
      file: ../docker/compose.common.yaml
      service: common
    links:
      - sonarr
      - radarr
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ${APP_PATH}/recyclarr:/config
      - ./recyclarr.yaml:/config/recyclarr.yaml
      - ./secrets.yaml:/config/secrets.yaml
